[package]
name = "pianoctl"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
clap = { workspace = true, features = ["env"] }
toml = "0.9"
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
alsa.workspace = true
chrono.workspace = true

[dev-dependencies]
jsonschema = { version = "0.35", default-features = false }
